site_name: ML Journey — Muhammad Luqman Hakim
site_description: Portfolio and learning journal of a machine learning enthusiast
site_author: Muhammad Luqman Hakim
theme:
  name: material
  palette:
    - scheme: default
      primary: deep purple
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tabs
    - search.highlight
    - content.code.annotate
    - content.action.edit

nav:
  - Home: index.md
  - About: about.md

